name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run test
        env:
          TOKEN: ${{ secrets.TEST_TOKEN }}
          ADDRESS: ${{ secrets.TEST_ADDRESS }}
          PORT: ${{ secrets.TEST_PORT }}
          SECURE: true
          DEBUG: true
          SECRET: ${{ secrets.TEST_SECRET }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}