name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node Latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm run test
        env:
          ADMIN_TOKEN: ${{ secrets.TEST_ADMIN_TOKEN }}
          CLIENT_TOKEN: ${{ secrets.TEST_CLIENT_TOKEN }}
          ADDRESS: ${{ secrets.TEST_ADDRESS }}
          PORT: ${{ secrets.TEST_PORT }}
          SECURE: true
          DEBUG: true
          SECRET: ${{ secrets.TEST_SECRET }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}